environment:
    matrix:
        - PYTHON: "C:\\Python27"

build: off

install:
    - "%PYTHON%\\python.exe -m pip install tox"

test_script:
    - '%PYTHON%\\python.exe -c "import sys; print sys.platform"'
    - "%PYTHON%\\Scripts\\tox.exe"

on_failure:
    - appveyor PushArtifact ".tox\\core_logger\\core_logger.log"
